// <auto-generated />
using System;
using AnnouncementBoard.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnnouncementBoard.DAL.Migrations
{
    [DbContext(typeof(AnnouncementBoardDbContext))]
    [Migration("20250610125119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnnouncementBoard.DAL.Entitys.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("AnnouncementBoard.DAL.Entitys.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Побутова техніка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Комп'ютерна техніка"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Смартфони"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Інше"
                        });
                });

            modelBuilder.Entity("AnnouncementBoard.DAL.Entitys.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Холодильники"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Пральні машини"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Бойлери"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Печі"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Витяжки"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Мікрохвильові печі"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "ПК"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Ноутбуки"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Монітори"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Принтери"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Сканери"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Android смартфони"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "iOS/Apple смартфони"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Name = "Одяг"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Name = "Взуття"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Name = "Аксесуари"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Name = "Спортивне обладнання"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Name = "Іграшки"
                        });
                });

            modelBuilder.Entity("AnnouncementBoard.DAL.Entitys.Announcement", b =>
                {
                    b.HasOne("AnnouncementBoard.DAL.Entitys.Category", "Category")
                        .WithMany("Announcements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnnouncementBoard.DAL.Entitys.SubCategory", "SubCategory")
                        .WithMany("Announcements")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("AnnouncementBoard.DAL.Entitys.SubCategory", b =>
                {
                    b.HasOne("AnnouncementBoard.DAL.Entitys.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AnnouncementBoard.DAL.Entitys.Category", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("AnnouncementBoard.DAL.Entitys.SubCategory", b =>
                {
                    b.Navigation("Announcements");
                });
#pragma warning restore 612, 618
        }
    }
}
